version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8496:80"

  npm:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm

  dev:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run dev
    ports:
      - "3030:3030"

  server:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run server
    ports:
      - "3000:3000"
